name: Build and Deploy
on:
  push:
    branches:
      - '0.14'
      - '0.13'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install and Build
        run: |
          npm install;
          npm run check-links;
          echo 'docs.cosmwasm.com' > CNAME;
          mkdir -p ~/output/public;
          cp -r .vuepress/public/* ~/output;
          while read -r branch path_prefix; do \
            (git checkout ${branch} && npm install && VUEPRESS_BASE="/${path_prefix}/" npm run build); \
            mkdir -p ~/output/${path_prefix}; \
            cp -r .vuepress/dist/* ~/output/${path_prefix}/; \
            cp ~/output/${path_prefix}/index.html ~/output; \
          done < versions;

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ~/output/
